### ISSUE TITLE
Add an option to set image size

### ISSUE THREAD

**Issue by aledeg** [aledeg/FreshRSS-extensions#4]
See #1

**Comment by ghost** [comment]
does not seems to work with the default value, I still have large image displayed.

**Comment by aledeg** [comment]
You have to save it first because the default value is not stored until then. When you save it, it generates a css file to include in the page. You can validate if it is downloaded in the network console. You should see something similar to ```https://www.example.org/ext.php?f=xExtension-RedditImage%2Fstatic%2Fstyle.user.css&t=css&1564383969```.

Let me know if that solves your problem!

**Comment by ghost** [comment]
it does not solve my issue, and I have just seen that if I change the value from 70 to 50 and click save, it rollback to 70

**Comment by aledeg** [comment]
I've seen that but it's only on the config page. If you check the feeds, the configuration will apply. There is some kind of cache somewhere but I don't know where atm. If you log out and in again. It should work. If you have any info, please share!

**Comment by ghost** [comment]
Still not working for me. I am using yunohost, so I don't have option to disconnect.

**Comment by aledeg** [comment]
What happens when you force the page refresh?
What happens when you delete the cookie?

**Comment by ghost** [comment]
nothing more, I've deleted the cookie, also the force refresh did not change anything

**Comment by ghost** [comment]
I had to go again to the image setting to put a new value now it is working and save properly.

**Comment by aledeg** [comment]
Great! But I am frustrated not knowing what happens. I would like to know so I can fix it :/
