### ISSUE TITLE
[Request] Include v.redd.it Videos

### ISSUE THREAD

**Issue by rom-1** [aledeg/FreshRSS-extensions#6]
Hi,

first of all, thanks for creating and updating this extension! Most of the time, this works flawless for me. 
Unfortunately, it looks like if someone posts a video using v.reddit.it, the Video is not embedded. 

Example Screenshot: 
![2021-01-02_17h07_00](https://user-images.githubusercontent.com/37835829/103461210-f92f9400-4d1c-11eb-9fdc-f943f6334ebf.png)

Any chance that this can be fixed?

Thanks!

**Comment by aledeg** [comment]
My pleasure :)
I'll seen what I can do. I let you know.
PR welcome!

**Comment by aledeg** [comment]
Do you have any feed I can use to do that?

**Comment by rom-1** [comment]
Very difficult, as Reddit is very "quick" and fast with their RSS Feeds. You can try these for example:

- https://www.reddit.com/r/funny/top.rss
- https://www.reddit.com/r/memes/top.rss
- https://www.reddit.com/r/nextfuckinglevel/top.rss

--> maybe do a quick "CTRL+F" Text search for "v.redd.it" to see if there is currently a video link within that Feed. If yes, add it to FreshRSS.

**Comment by aledeg** [comment]
This will be supported in the next release. The support is not perfect because I couldn't find the source of the file. I had to rely on the fallback value provided in the json response.
If there is a better way to do that, let me know.

**Comment by rom-1** [comment]
Thank you very much :)

**Comment by aledeg** [comment]
My pleasure

**Comment by aledeg** [comment]
New version released
