### ISSUE TITLE
[Bug Report] imgur gifs don't load properly

### ISSUE THREAD

**Issue by rom-1** [aledeg/FreshRSS-extensions#8]
![2021-01-04_10h26_21](https://user-images.githubusercontent.com/37835829/103520383-5dff0180-4e77-11eb-9710-ecc92a738dea.png)
Example Feed: http://reddit.com/r/gifs/top.rss

Example Post: https://www.reddit.com/r/gifs/comments/kpiapr/mate_of_mine_with_the_one_in_a_million_coaster/

This post links to https://i.imgur.com/21p2Mj5.gifv

You plugin loads the static gif (first frame only) from https://i.imgur.com/21p2Mj5.gif, but does not load/embed the gifv file.

**Comment by aledeg** [comment]
This will be addressed in the next release.

**Comment by aledeg** [comment]
New version released
